apiVersion: v1
kind: ConfigMap
metadata:
  name: file-sd-config
  namespace: monitoring
data:
  kafka-metrics.json: |
    [
        {
            "targets": ["10.127.92.103:9308"],
            "labels": {
                "instance": "10.127.92.103"
            }
        },
        {
            "targets": ["10.127.92.104:9308"],
            "labels": {
                "instance": "10.127.92.104"
            }
        },
        {
            "targets": ["10.127.92.105:9308"],
            "labels": {
                "instance": "10.127.92.105"
            }
        }
    ]
  system-metrics.json: |
    [
        {
            "targets": ["10.127.92.100:9101"],
            "labels": {
                "instance": "10.127.92.100"
            }
        },
        {
            "targets": ["10.127.92.101:9101"],
            "labels": {
                "instance": "10.127.92.101"
            }
        },
        {
            "targets": ["10.127.92.102:9101"],
            "labels": {
                "instance": "10.127.92.102"
            }
        },
        {
            "targets": ["10.127.92.103:9101"],
            "labels": {
                "instance": "10.127.92.103"
            }
        },
        {
            "targets": ["10.127.92.104:9101"],
            "labels": {
                "instance": "10.127.92.104"
            }
        },
        {
            "targets": ["10.127.92.105:9101"],
            "labels": {
                "instance": "10.127.92.105"
            }
        },
        {
            "targets": ["10.127.92.106:9101"],
            "labels": {
                "instance": "10.127.92.106"
            }
        },
        {
            "targets": ["10.127.92.107:9101"],
            "labels": {
                "instance": "10.127.92.107"
            }
        },
        {
            "targets": ["10.127.92.108:9101"],
            "labels": {
                "instance": "10.127.92.108"
            }
        },
        {
            "targets": ["10.127.91.24:9101"],
            "labels": {
                "instance": "10.127.91.24"
            }
        },
        {
            "targets": ["10.127.91.25:9101"],
            "labels": {
                "instance": "10.127.91.25"
            }
        },
        {
            "targets": ["10.127.91.26:9101"],
            "labels": {
                "instance": "10.127.91.26"
            }
        },
        {
            "targets": ["10.127.91.27:9101"],
            "labels": {
                "instance": "10.127.91.27"
            }
        },
        {
            "targets": ["10.127.91.28:9101"],
            "labels": {
                "instance": "10.127.91.28"
            }
        },
        {
            "targets": ["10.127.91.29:9101"],
            "labels": {
                "instance": "10.127.91.29"
            }
        },
        {
            "targets": ["10.127.91.30:9101"],
            "labels": {
                "instance": "10.127.91.30"
            }
        }
    ]