apiVersion: v1
kind: ConfigMap
metadata:
  name: file-sd-config
  namespace: monitoring
data:
  kafka-metrics.json: |
    [
        {
            "targets": ["10.127.92.103:9308"],
            "labels": {
                "instance": "10.127.92.103"
            }
        },
        {
            "targets": ["10.127.92.104:9308"],
            "labels": {
                "instance": "10.127.92.104"
            }
        },
        {
            "targets": ["10.127.92.105:9308"],
            "labels": {
                "instance": "10.127.92.105"
            }
        }
    ]